version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql